
networks:
  service:
    name: trip-service-main
  architecture:
    name: main

services:
  ## Rest API
  rest-api-trip1:
    networks:
      - service
      - architecture
    build: ./rest_api
    container_name: rest-api-trip1
    ports:
      - 8003:8000
