[package]
name = "CircuitBrekaer"
version = "0.1.0"
authors = ["Tim Hoeffner <tim.florian.hoeffner@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
wasm-bindgen-futures = "0.4.33"
js-sys = "0.3.60"
chrono = "0.4.23"
